#!/bin/sh

echo '[git hook] executing gradle spotlessApply before commit'

# stash any unstaged changes
git stash -q --keep-index

# run the spotlessApply with the gradle wrapper
./gradlew spotlessApply --daemon

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

echo ''

# return the './gradlew spotlessApply' exit code
exit $RESULT
