import React from 'react';
import { GraphQL, GraphQLProvider, useGraphQL } from 'graphql-react';
import { useParams } from "react-router-dom";

import Loader from '../Loader';
import CollectionForm from '../forms/CollectionForm';
import { reactOptions } from './reactOptions';

const CollectionGraphQL = ({databaseName, collectionName}) => {

  const query = `
    {
      collectionByNamespace(databaseName: "${databaseName}", collectionName: "${collectionName}") {
        databaseName
        collectionName
        jsonSchema
        isSchemaAutoGenerated
        uiSchema
      }
    }
  `;


  // Memoization allows the `useGraphQL` hook to avoid work in following renders
  // with the same GraphQL operation.
  const operation = React.useMemo(
    () => ({
      query,
      variables: {
      },
    }),
    [databaseName, collectionName]
  );

    // The `useGraphQL` hook can be used for both queries and mutations.
  const { loading, cacheValue: { data, ...errors } = {} } = useGraphQL({
    operation,
    fetchOptionsOverride: reactOptions,
    loadOnMount: true,
    loadOnReload: true,
    loadOnReset: true
  });

  return (
    <>
    {data && (
      <CollectionForm data={data.collectionByNamespace} />
      )}
    {loading && <Loader />}
    </>
  );
}

export default function MongoCollection() {
  let { databaseName, collectionName } = useParams();
  return (
    <CollectionGraphQL databaseName={databaseName} collectionName={collectionName} />
  );
};
