import React from 'react';
import { GraphQL, GraphQLProvider, useGraphQL } from 'graphql-react';
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TablePagination from '@material-ui/core/TablePagination';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';
import { useParams } from "react-router-dom";

import Loader from '../Loader';
import CollectionForm from '../forms/CollectionForm';
import { reactOptions } from './reactOptions';
import { defaultStyles } from '../styles';

const CollectionGraphQL = ({databaseName, collectionName}) => {

  const query = `
    {
      collectionByNamespace(databaseName: "${databaseName}", collectionName: "${collectionName}") {
        jsonSchema
        isSchemaAutoGenerated
        uiSchema
      }
    }
  `;


  // Memoization allows the `useGraphQL` hook to avoid work in following renders
  // with the same GraphQL operation.
  const operation = React.useMemo(
    () => ({
      query,
      variables: {
      },
    }),
    [databaseName, collectionName]
  );

    // The `useGraphQL` hook can be used for both queries and mutations.
  const { loading, cacheValue: { data, ...errors } = {} } = useGraphQL({
    operation,
    fetchOptionsOverride: reactOptions,
    loadOnMount: true,
    loadOnReload: true,
    loadOnReset: true
  });

  const classes = defaultStyles();

  console.log("DATA: ", data)
  return (
    <>
    {data && (
      <CollectionForm jsonSchema={data.collectionByNamespace.jsonSchema} uiSchema={data.collectionByNamespace.uiSchema} />
      )}
    {loading && <Loader />}
    </>
  );
}

export default function MongoCollection() {
  const graphql = new GraphQL();
  let { databaseName, collectionName } = useParams();
  return (
    <CollectionGraphQL databaseName={databaseName} collectionName={collectionName} />
  );
};
